spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/repair_tracking_dev_db
    username: postgres
    password: ${postgres_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8088
